spring.application.name=ecommerce
spring.jpa.properties.hibernate.format_sql=true
server.port=8080

# Banco
spring.datasource.url=jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:ecommerce}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:admin}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Para servir arquivos da pasta /uploads dentro do container
# spring.web.resources.static-locations=file:/uploads/


# --- servidor de email fake que intercepta o envio do email, em teoria funcionaria de fosse um dominio valido ---

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=6c7ed67d53452b17e569c6024fb2af0a
spring.mail.password=6c7ed67d53452b17e569c6024fb2af0a
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=noreply@catalogo.com

