spring.application.name=ecommerce
spring.datasource.url=jdbc:postgresql://localhost:5432/db_ecommerce
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- servidor de email fake que intercepta o envio do email, em teoria funcionaria de fosse um dominio valido ---

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=6c7ed67d53452b17e569c6024fb2af0a
spring.mail.password=6c7ed67d53452b17e569c6024fb2af0a
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=noreply@catalogo.com

